# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0
# terok:container — this file is deployed into task containers, not used on the host.

"""Idempotently add a path to Vibe's ``trusted_folders.toml``.

Usage:
    python3 terok-trust-workspace.py <path-to-trust> <toml-file>

Reads the existing TOML (preserving any keys other than ``trusted`` /
``untrusted``), appends ``<path-to-trust>`` to the ``trusted`` array
unless already present, and rewrites the file.

The caller is expected to ``flock`` the file before invoking this
script — ``~/.vibe/trusted_folders.toml`` is shared across every
terok task container, so concurrent writes without external locking
would corrupt the TOML.

Why a separate script (rather than inline Python in each wrapper):
both the CLI wrapper (generated by
``terok_executor.provider.wrappers``) and the ACP wrapper
(``resources/scripts/terok-vibe-acp``) need the same TOML merge.
Inlining duplicated the logic; this file is the single home so
future Vibe schema changes only need to land once.

Exits 0 on success or "already trusted"; exits 0 silently when the
container's Python is too old to provide ``tomllib`` (Python < 3.11
ships in nothing terok currently builds against, but the import
guard keeps the script harmless if that changes).
"""

from __future__ import annotations

import pathlib
import sys

try:
    import tomllib
except ImportError:
    sys.exit(0)  # py<3.11: no stdlib reader, skip the merge

# Optional writer.  Without a real TOML serializer we fall back to a
# minimal renderer that handles only the two keys Vibe defines today,
# and unknown keys are dropped — matching Vibe's own
# ``TrustedFoldersManager._save`` behaviour but losing any future
# extensions.  ``tomli_w`` is the preferred wheel; ``toml`` is the
# fallback that older environments ship.
_dump = None
for _mod_name in ("tomli_w", "toml"):
    try:
        _mod = __import__(_mod_name)
    except ImportError:
        continue
    if hasattr(_mod, "dumps"):
        _dump = _mod.dumps
        break


def _arr(xs: list[str]) -> str:
    """Render a list of strings as a single-line TOML array."""
    return "[" + ", ".join('"' + x.replace('"', '\\"') + '"' for x in xs) + "]"


def _minimal_dump(data: dict) -> str:
    """Render ``data`` using only the keys Vibe declares today.

    Unknown keys are lost — same trade-off as Vibe's own
    ``TrustedFoldersManager._save``.  When ``tomli_w`` is available
    the full ``data`` round-trips losslessly via that writer instead.
    """
    return (
        "trusted = " + _arr(list(data.get("trusted", []))) + "\n"
        "untrusted = " + _arr(list(data.get("untrusted", []))) + "\n"
    )


def main(target: str, tf_path: pathlib.Path) -> int:
    """Add *target* to ``trusted`` in *tf_path*; return process exit code."""
    data = tomllib.loads(tf_path.read_text()) if tf_path.is_file() else {}
    trusted = list(data.get("trusted", []))
    if target in trusted:
        return 0
    trusted.append(target)
    data["trusted"] = trusted
    data.setdefault("untrusted", list(data.get("untrusted", [])))

    payload = _dump(data) if _dump is not None else _minimal_dump(data)
    tf_path.write_text(payload)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], pathlib.Path(sys.argv[2])))
